### ISSUE TITLE
Unable to change room history visibility.

### ISSUE THREAD

**Issue by michaelkaye** [matrix-org/trafficlight-adapter-element-web#24]
```
AssertionError: Timed out retrying after 45000ms: Expected to find element: `[data-test-id=base-card-close-button]`, but never found it.
    at changeRoomHistoryVisibility (webpack:///./cypress/e2e/trafficlight/actions/room.ts:50:7)
    at runAction (webpack:///./cypress/e2e/trafficlight/trafficlight.spec.ts:167:47)
    at Context.eval (webpack:///./cypress/e2e/trafficlight/trafficlight.spec.ts:91:21)
In file unknown
```

**Comment by michaelkaye** [comment]
https://github.com/matrix-org/matrix-react-sdk/commit/880a86c8b177e4d9ab1f60b5386db6c80efb0bbf

looks like a widespread s/data-test-id/data-testid/ has been slowly occurring.
